- name: Create Dashboard File
  ansible.builtin.template:
    src: dashboard.json
    dest: /tmp/dashboard.json

- name: Add Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.21.207:3000
#    grafana_api_key: "{{ lookup('amazon.aws.aws_ssm', 'grafana.api_key', region='us-east-1' ) }}"
    grafana_api_key: "glsa_T5Lttd3Bh999NCHuVa1k90NsaUN2Epl7_4320db3e"
    state: present
    commit_message: Updates by ansible
    overwrite: true
    path: /tmp/dashboard.json